development:
  adapter: postgresql
  database: knapsack_development
  pool: 5
  username: metzbr1
  host: localhost 
 
test:
  adapter: postgresql
  database: knapsack_test
  pool: 5
  username: metzbr1
  host:  localhost
 
production:
  adapter: postgresql
  encoding: utf8
  database: menudb
  username: bmetzger
  password: rufio123
  host: menudb.cctul6uu1y0k.us-west-2.rds.amazonaws.com
  port: 5432